"""Declarative base shared by every SQLAlchemy model.

The naming convention here is the one Alembic recommends — it makes
autogenerated constraint/index names deterministic across runs, so
migrations stay clean and reviewable.
"""

from datetime import datetime, timezone

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase


NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def utcnow() -> datetime:
    """Timezone-aware UTC `now()` for model defaults.

    We never store naive datetimes — every timestamp column is `timestamptz`
    in Postgres, which round-trips with `datetime.now(timezone.utc)` losslessly.
    """
    return datetime.now(timezone.utc)
